<?php
/**
 * Spain states
 */
global $states;

$states["ES"] = array(
    'C' => __('A Coru&ntilde;a', 'socialbet'),
    'VI' => __('Araba/&Aacute;lava', 'socialbet'),
    'AB' => __('Albacete', 'socialbet'),
    'A' => __('Alicante', 'socialbet'),
    'AL' => __('Almer&iacute;a', 'socialbet'),
    'O' => __('Asturias', 'socialbet'),
    'AV' => __('&Aacute;vila', 'socialbet'),
    'BA' => __('Badajoz', 'socialbet'),
    'PM' => __('Baleares', 'socialbet'),
    'B' => __('Barcelona', 'socialbet'),
    'BU' => __('Burgos', 'socialbet'),
    'CC' => __('C&aacute;ceres', 'socialbet'),
    'CA' => __('C&aacute;diz', 'socialbet'),
    'S' => __('Cantabria', 'socialbet'),
    'CS' => __('Castell&oacute;n', 'socialbet'),
    'CE' => __('Ceuta', 'socialbet'),
    'CR' => __('Ciudad Real', 'socialbet'),
    'CO' => __('C&oacute;rdoba', 'socialbet'),
    'CU' => __('Cuenca', 'socialbet'),
    'GI' => __('Girona', 'socialbet'),
    'GR' => __('Granada', 'socialbet'),
    'GU' => __('Guadalajara', 'socialbet'),
    'SS' => __('Gipuzkoa', 'socialbet'),
    'H' => __('Huelva', 'socialbet'),
    'HU' => __('Huesca', 'socialbet'),
    'J' => __('Ja&eacute;n', 'socialbet'),
    'LO' => __('La Rioja', 'socialbet'),
    'GC' => __('Las Palmas', 'socialbet'),
    'LE' => __('Le&oacute;n', 'socialbet'),
    'L' => __('Lleida', 'socialbet'),
    'LU' => __('Lugo', 'socialbet'),
    'M' => __('Madrid', 'socialbet'),
    'MA' => __('M&aacute;laga', 'socialbet'),
    'ML' => __('Melilla', 'socialbet'),
    'MU' => __('Murcia', 'socialbet'),
    'NA' => __('Navarra', 'socialbet'),
    'OR' => __('Ourense', 'socialbet'),
    'P' => __('Palencia', 'socialbet'),
    'PO' => __('Pontevedra', 'socialbet'),
    'SA' => __('Salamanca', 'socialbet'),
    'TF' => __('Santa Cruz de Tenerife', 'socialbet'),
    'SG' => __('Segovia', 'socialbet'),
    'SE' => __('Sevilla', 'socialbet'),
    'SO' => __('Soria', 'socialbet'),
    'T' => __('Tarragona', 'socialbet'),
    'TE' => __('Teruel', 'socialbet'),
    'TO' => __('Toledo', 'socialbet'),
    'V' => __('Valencia', 'socialbet'),
    'VA' => __('Valladolid', 'socialbet'),
    'BI' => __('Bizkaia', 'socialbet'),
    'ZA' => __('Zamora', 'socialbet'),
    'Z' => __('Zaragoza', 'socialbet')
); 
