<?php global $wpdb, $sbdb, $SocBet_Theme; ?>

<div class="wrap">

	<h2><?php printf(__('Add New Market for "%s"', 'socialbet'), $event->post_title ); ?>
		<a href="<?php echo admin_url('edit.php?post_type=event&page=show-markets&event='.$event->ID);?>" class="add-new-h2"><?php print __('Cancel', 'socialbet'); ?></a>
	</h2>

	<br />

	<?php $SocBet_Theme->print_messages( $errors ); ?>

	<form id="socbet-nwe-market" method="post" action="<?php echo admin_url('edit.php?post_type=event&page=create-market&event='.$event->ID);?>">

		<?php wp_nonce_field( 'socbet-new-market', '_wpnonce', true, true ); #security ?>
		<input type="hidden" name="event_id" value="<?php echo esc_attr( $event->ID ); ?>" />
		<p>
			<label for="market-name"><?php _e('Market Name', 'socialbet'); ?></label>
			<input type="text" name="market_name" id="market-name" class="socbet-form" value="" placeholder="<?php _e('Enter the Market Name here', 'socialbet'); ?>" autocomplete="off" />
		</p>

		<h4><?php print __('Market Entries and Odds', 'socialbet'); ?></h4>

		<div id="market-entries-wrap">

			<div id="market-entries-form">
				<div class="col-wrap">
					<div class="col-md-3">
						<input type="text" name="new_market_entry_name" id="new_market_entry_name" value="" placeholder="<?php print __('Market Entry Name', 'wip'); ?>" />
					</div>
					<div class="col-md-3">
						<input type="text" name="new_market_entry_odds" id="new_market_entry_odds" value="" placeholder="<?php print __('Odds', 'wip'); ?>" />
					</div>
					<div class="col-md-3">
						<input type="text" name="new_market_entry_decimal_odds" id="new_market_entry_decimal_odds" value="" placeholder="<?php print __('Decimal Odds', 'wip'); ?>" />
					</div>
					<div class="col-md-3">
						<input type="text" name="new_market_entry_price" id="new_market_entry_price" value="" placeholder="<?php print __('Price', 'wip'); ?>" />
					</div>
				</div>
				<p class="text-right">
					<a id="add-new-market-entry" class="button button-primary" href="#"><?php print __('Add New', 'socialbet'); ?></a>
				</p>
			</div>

			<table class="wp-list-table widefat fixed">
				<thead>
					<tr>
						<th scope="col" class="manage-column"><?php print __('Market Entry', 'socialbet'); ?></th>
						<th scope="col" class="manage-column"><?php print __('Odds', 'socialbet'); ?></th>
						<th scope="col" class="manage-column"><?php print __('Decimal Odds', 'socialbet'); ?></th>
						<th scope="col" class="manage-column"><?php print __('Price', 'socialbet'); ?></th>
						<th scope="col" class="manage-column"><?php print __('Action', 'socialbet'); ?></th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th scope="col" class="manage-column"><?php print __('Market Entry', 'socialbet'); ?></th>
						<th scope="col" class="manage-column"><?php print __('Odds', 'socialbet'); ?></th>
						<th scope="col" class="manage-column"><?php print __('Decimal Odds', 'socialbet'); ?></th>
						<th scope="col" class="manage-column"><?php print __('Price', 'socialbet'); ?></th>
						<th scope="col" class="manage-column"><?php print __('Action', 'socialbet'); ?></th>
					</tr>
				</tfoot>

				<tbody id="the-list-markets">

						<tr id="socbet-noentry">
							<td colspan="5">
								<div class="socbet-alert alert-warning text-center"><?php print __('No data!', 'socialbet'); ?></div>
							</td>
						</tr>
				</tbody>
			</table>
		</div>

		<p class="submit">
			<input type="submit" class="button button-primary" name="submit" value="<?php _e('Save Data', 'socialbet'); ?>" />
		</p>
	</form>

</div>